name: Docker Compose Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List directory contents
      run: ssh -o StrictHostKeyChecking=no root@45.41.204.244 'ls -l /home/NextJS'

    - name: Set up SSH keys
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.KEY_PRIVATE }}

    - name: Execute deployment script on VPS
      run: ssh -o StrictHostKeyChecking=no root@45.41.204.244 'bash -s' < RagaWeb.sh