name: Docker Compose Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into server and run Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: 45.41.204.244
          username: root
          key: RagaWeb#2036VPS
          port: 22
          script: |
            cd /home/NextJS/
            ./RagaWeb.sh